# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.form.type.local_datetime:
        class: AppBundle\FormType\LocalDateTimeType
        tags:
            - { name: form.type, alias: local_datetime }

    app.hash_generator:
        class: AppBundle\Service\hashGenerator
        arguments: ['@doctrine.orm.entity_manager']

    app.generate_payment_status_list:
        class: AppBundle\Service\generatePaymentStatusList
        arguments: ['@doctrine.orm.entity_manager', '@buzz']

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }