# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.form.type.local_datetime:
        class: AppBundle\FormType\LocalDateTimeType
        tags:
            - { name: form.type, alias: local_datetime }

    app.hash_generator:
        class: AppBundle\Service\hashGenerator
        arguments: ['@doctrine.orm.entity_manager']

    app.generate_payment_status_list:
        class: AppBundle\Service\generatePaymentStatusList
        arguments: ['@doctrine.orm.entity_manager']

    app.get_exchange_rates:
        class: AppBundle\Service\fixerExchangeRates
        arguments: ['@buzz']

    app.get_budget:
        class: AppBundle\Service\generateBudget
        arguments: ['@doctrine.orm.entity_manager']

    app.get_variables:
        class: AppBundle\Service\getVariables
        arguments: ['@doctrine.orm.entity_manager']

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }